### ISSUE TITLE
Vanilla tag leftovers still remain

### ISSUE THREAD

**Issue by sternschnaube** [CamperSamu/WhereAreYouFrom#10]
I was making a use of the new config options - everything worked great.
But some items are still having the Minecraft tag. As it seems for now, just tools and armor items. 

![image](https://github.com/CamperSamu/WhereAreYouFrom/assets/120551916/bd8e041e-a00e-4e28-afed-825e2eb4e523)

**Comment by venaminecraft** [comment]
It seems that reconnecting to the server / restarts solving the problem itself 😊

**Comment by CamperSamu** [comment]
dropping the item and picking it back up also works, the nuclear option is to log in with the item in the inventory since it triggers NBT cleaning for all items in the player's inventory

**Comment by venaminecraft** [comment]
Thanks for clarifying!!

**Comment by CamperSamu** [comment]
I don't run that after a server reboot with a config change because it can be a stressing operation with millions of items loaded, but I am looking into ways to implement this cleanly (my current idea is to execute that function at world loading inside the method that loads all items in the world when the config checksum doesn't match)

**Comment by venaminecraft** [comment]
Otherwise maybe a command would do it too - then the user can decide when it's the right time for that.

But I'm sure you'll come up with an elegant way of it 😊
