### ISSUE TITLE
Publish 1.19.x builds on Modrinth:)

### ISSUE THREAD

**Issue by ghost** [CamperSamu/WhereAreYouFrom#7]

**Comment by CamperSamu** [comment]
I decided to not publish builds of this mod for 1.19.x due to [a bug caused by creative mode that I finally got around to fix](src/main/java/com/campersamu/shoutout/mixin/CleanNbtFix.java) and due to a lack of time to maintain the mod.
I am slowly getting everything up to speed and I am planning on publishing a 1.20.4 version of all my mods on Modrinth only.

I am also planning on making a shared internal lib to make mod updates and version indipendency easier, but no promise on this since I still don't have too much time.
